### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by kingLeicester** [muschellij2/freesurfer#8]
Hello! I am trying to convert .mgz to .obj. I installed your wrapper using both

1. devtools::install_github("muschellij2/freesurfer") and

2. install.packages("freesurfer")

but when I do 

library(freesurfer) and

do have_fs(), it returns FALSE. 

Would you be able to help me troubleshoot this? Thanks!

**Comment by muschellij2** [comment]
You need to install freesurfer.
John
