### ISSUE TITLE
recon-all error

### ISSUE THREAD

**Issue by snaillyd** [muschellij2/freesurfer#9]
Hi, I got an error message when I use scipt 'recon_all(infile = paste0(detination,ID,'.nii.gz'),subjid=ID,verbose = TRUE,opts = '-all')'
The error message is:
sh: 66: /usr/local/freesurfer/FreeSurferEnv.sh: [[: not found
sh: 66: /usr/local/freesurfer/FreeSurferEnv.sh: -z: not found
sh: 86: /usr/local/freesurfer/FreeSurferEnv.sh: [[: not found
sh: 119: /usr/local/freesurfer/FreeSurferEnv.sh: [[: not found
sh: 119: /usr/local/freesurfer/FreeSurferEnv.sh: 0: not found
sh: 123: /usr/local/freesurfer/FreeSurferEnv.sh: [[: not found
sh: 123: /usr/local/freesurfer/FreeSurferEnv.sh: 0: not found
sh: 127: /usr/local/freesurfer/FreeSurferEnv.sh: Syntax error: word unexpected (expecting "then")

Could you help me out?

**Comment by muschellij2** [comment]
Are you running this in `RStudio` or the Terminal?

**Comment by snaillyd** [comment]
I tried running this in both RStudio and R Terminal，and got the same error message. However, no error presented when I use freesurfer recon-all in Terminal.

**Comment by muschellij2** [comment]
**Can you provide a MCVE?**


It seems as though you should be calling `bash`, but it's not.  Do you have specific things done in your `.profile` or `.bash_profile` or `.bashrc` that change environment variables?

Can you also provide the output of this code:
```r
freesurferdir = Sys.getenv("FREESURFER_HOME")
freesurferdir
head(readLines("/usr/local/freesurfer/FreeSurferEnv.sh"), 3)
freesurfer::fs_version()
```

**Comment by snaillyd** [comment]
![image](https://user-images.githubusercontent.com/28690261/57784736-fefcee00-7762-11e9-91fd-2907c33f17a6.png)

**Comment by snaillyd** [comment]
![image](https://user-images.githubusercontent.com/28690261/57784824-2b186f00-7763-11e9-97c2-dc1548fa2192.png)

**Comment by muschellij2** [comment]
Seems as though bash should be called here.  I don't know why it's
failing.  The .sh file would fail if run by sh, so I understand why that
may be the case.  This may be related to `source` vs. `.` as is related to
https://github.com/muschellij2/freesurfer/issues/6.
Can you run

```r
system("source /usr/local/freesurfer/FreeSurferEnv.sh")
system(". /usr/local/freesurfer/FreeSurferEnv.sh")
system("sh /usr/local/freesurfer/FreeSurferEnv.sh")
```
in R and give output?

John

**Comment by muschellij2** [comment]
Seems as though bash should be called here.  I don't know why it's
failing.  The .sh file would fail if run by sh, so I understand why that
may be the case.  This may be related to `source` vs. `.` as is related to
https://github.com/muschellij2/freesurfer/issues/6.
Can you run

```r
system("source /usr/local/freesurfer/FreeSurferEnv.sh")
system(". /usr/local/freesurfer/FreeSurferEnv.sh")
system("sh /usr/local/freesurfer/FreeSurferEnv.sh")
```

in R and give output?

**Comment by snaillyd** [comment]
![image](https://user-images.githubusercontent.com/28690261/57814854-a56ae280-77a7-11e9-8931-a9531aed5def.png)

**Comment by muschellij2** [comment]
Please run that in Terminal R and provide output.

Also try
system("bash /usr/local/freesurfer/FreeSurferEnv.sh")
John
